server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: concession-service
          uri: lb://concession-service
          predicates:
            - Path=/api/concession/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: kitchen-service
          uri: lb://kitchen-service
          predicates:
            - Path=/api/kitchen/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/